// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.identity().name("player_id"),
  gameSlug: __t.string().name("game_slug"),
  lastVisitAt: __t.u64().name("last_visit_at"),
  isFavorite: __t.bool().name("is_favorite"),
  hasLiked: __t.bool().name("has_liked"),
  visitCount: __t.u32().name("visit_count"),
});
