// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameActivity = __t.object("GameActivity", {
  playerId: __t.identity(),
  gameSlug: __t.string(),
  lastVisitAt: __t.u64(),
  isFavorite: __t.bool(),
  hasLiked: __t.bool(),
  visitCount: __t.u32(),
});
export type GameActivity = __Infer<typeof GameActivity>;

export const GameStats = __t.object("GameStats", {
  gameSlug: __t.string(),
  totalHearts: __t.u64(),
  totalVisits: __t.u64(),
});
export type GameStats = __Infer<typeof GameStats>;

export const GameVisit = __t.object("GameVisit", {
  playerId: __t.identity(),
  gameSlug: __t.string(),
  visitedAt: __t.u64(),
});
export type GameVisit = __Infer<typeof GameVisit>;

export const MyActivity = __t.object("MyActivity", {});
export type MyActivity = __Infer<typeof MyActivity>;

export const Profile = __t.object("Profile", {
  id: __t.identity(),
  xp: __t.u64(),
  level: __t.u32(),
});
export type Profile = __Infer<typeof Profile>;

