// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Firefly = __t.object("Firefly", {
  playerId: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  location: __t.string(),
  lastSeen: __t.u64(),
});
export type Firefly = __Infer<typeof Firefly>;

export const GameStats = __t.object("GameStats", {
  gameSlug: __t.string(),
  totalHearts: __t.u64(),
  totalVisits: __t.u64(),
});
export type GameStats = __Infer<typeof GameStats>;

export const MyActivity = __t.object("MyActivity", {
  id: __t.u64(),
  playerId: __t.identity(),
  gameSlug: __t.string(),
  lastVisitAt: __t.u64(),
  isFavorite: __t.bool(),
  hasLiked: __t.bool(),
  visitCount: __t.u32(),
});
export type MyActivity = __Infer<typeof MyActivity>;

export const Profile = __t.object("Profile", {
  id: __t.identity(),
  xp: __t.u64(),
  level: __t.u32(),
  authenticated: __t.bool(),
  provider: __t.string(),
  displayName: __t.string(),
  email: __t.string(),
  lastLoginAt: __t.u64(),
});
export type Profile = __Infer<typeof Profile>;

